# Site settings
title: Preservation Imagery
email: 
url: 
description: "Investigating the integrity and depreciation of glaciers in America"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Preservation Imagery

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: camera
    name: Don Kerrigan
    url: http://donkerrigan.com
  - title: github
    name: github
    url: https://github.com/preservation-imagery
  - title: tree
    name: Tyler Mitchell
    url: http://tylermitchell.xyz

# Build settings
markdown: kramdown
permalink: pretty
